apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  namespace: sonarqube
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/sonarqube-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - uspgh-neks-t4.amer.thermo.com
      containers:
        - image: sonarqube:lts-community
          name: sonarqube
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: 2000Mi
            limits:
              memory: 2000Mi
          volumeMounts:          # Adding volume mounts section here
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar
  name: sonar
  namespace: sonarqube
spec:
  type: NodePort
  ports:
    - port: 80       # Changed from 80 to 32050
      targetPort: 9000
      nodePort: 32050
      name: sonarport
  selector:
    app: sonarqube

